# Generated by Django 4.2.2 on 2023-07-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_id',
            new_name='id',
        ),
    ]
