# Generated by Django 4.2.2 on 2023-07-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Msg_id',
            new_name='msg_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='desc',
            field=models.IntegerField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
