# Generated by Django 4.2.2 on 2023-07-04 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_msg_id_contact_msg_id_alter_contact_desc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contact',
        ),
    ]
