# Generated by Django 4.2.2 on 2023-07-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_msg_id_contact_msg_id_alter_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Msg_id',
            new_name='msg_id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=60),
        ),
    ]
