# Generated by Django 4.2.2 on 2023-07-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_msg_id_contact_msg_id_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_json', models.CharField(max_length=5000)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=111)),
                ('Address', models.CharField(max_length=111)),
                ('city', models.CharField(max_length=111)),
                ('Zip_code', models.CharField(max_length=111)),
            ],
        ),
    ]
